### ISSUE TITLE
Support for arrays of arrays

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [HiDeoo/zod-matter#2]
### Describe the bug

I tried using zod matter on a markdown which includes an array of arrays. I already acknowledge it is an extreme case, yet I think: 
* If arrays of arrays must not supported by design, by zod-matter, then the error message should clearly state that: for the motment, `zod-matter` throws an error, stating that an array was expected, but an object was received. Which is not true, it is inded an array which was received, as expected
* If arrays of arrays must be supported by zod-matter, then we have here an actual bug.

### To Reproduce

So here is the code to reproduce the issue:

```TypeScript


const someMarkdown = `---\n
author: HiDeoo\n
andSomethingLikeThat:\n
  firstname: Jean-Baptiste\n
  lastname: Lasselle\n
  one: true\n
  two: 12\n
  three: false\n
  example1Categories: \n
    - design\n
    - terraform\n
    - plugin\n
  example2Categories: \n
    - first:\n
        - joe\n
        - alfred\n
        - alvin\n
    - second:\n
        - thirteen\n
        - hundred\n
        - books\n
    - third:\n
        - going\n
        - overseas\n
        - together\n
---\n
# Hello HiDeoo!
`


const exampleZodSchema1 = z.object({
  author: authorValue,
  andSomethingLikeThat: z.object({
    firstname: z.string(),
    lastname: z.string(),
    one: z.boolean(),//true
    two: z.number(),//12
    three: z.boolean(),//false
    example1Categories: z.array(z.string()),
    // example2Categories: z.array(z.array(z.string())).optional()
  })
})

const exampleZodSchema2 = z.object({
  author: authorValue,
  andSomethingLikeThat: z.object({
    firstname: z.string(),
    lastname: z.string(),
    one: z.boolean(),//true
    two: z.number(),//12
    three: z.boolean(),//false
    example1Categories: z.array(z.string()),
    example2Categories: z.array(z.array(z.string())).optional()
  })
})

const extractedFrontmatter1 = Test1.runTest1(someMarkdown, exampleZodSchema1)
const extractedFrontmatter2 = Test1.runTest1(someMarkdown, exampleZodSchema2)

/**
 * The first will work without error, because it does not try to parse the "example2Categories" array of arrays
 **/
console.log(` Final result : extractedFrontmatter1 =[${extractedFrontmatter1}]`)

/**
 * The second will throw an error, because it does try to parse the "example2Categories" array of arrays
 **/
console.log(` Final result : extractedFrontmatter2 =[${extractedFrontmatter2}]`)


``` 

The output of the error: 

```bash

ZodError: [
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "object",
    "path": [
      "andSomethingLikeThat",
      "example2Categories",
      0
    ],
    "message": "Expected array, received object"
  },
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "object",
    "path": [
      "andSomethingLikeThat",
      "example2Categories",
      1
    ],
    "message": "Expected array, received object"
  },
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "object",
    "path": [
      "andSomethingLikeThat",
      "example2Categories",
      2
    ],
    "message": "Expected array, received object"
  }
]
    at get error [as error] (...\node_modules\.pnpm\zod@3.23.8\node_modules\zod\lib\types.js:55:31)
    at ZodObject.parse (...\node_modules\.pnpm\zod@3.23.8\node_modules\zod\lib\types.js:160:22)
    at parseFrontMatter (...\node_modules\.pnpm\zod-matter@0.1.1_gray-matter@4.0.3_zod@3.23.8\node_modules\zod-matter\dist\index.cjs:48:18)
    at parse (...\node_modules\.pnpm\zod-matter@0.1.1_gray-matter@4.0.3_zod@3.23.8\node_modules\zod-matter\dist\index.cjs:37:10)
    at Test1.runTest1 (...\dist\ts.morph\lib\frontmatter\test1.js:16:49)
    at Object.<anonymous> (...\dist\index.js:520:45)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12) {
  issues: [
    {
      code: 'invalid_type',
      expected: 'array',
      received: 'object',
      path: [ 'andSomethingLikeThat', 'example2Categories', 0 ],
      message: 'Expected array, received object'
    },
    {
      code: 'invalid_type',
      expected: 'array',
      received: 'object',
      path: [ 'andSomethingLikeThat', 'example2Categories', 1 ],
      message: 'Expected array, received object'
    },
    {
      code: 'invalid_type',
      expected: 'array',
      received: 'object',
      path: [ 'andSomethingLikeThat', 'example2Categories', 2 ],
      message: 'Expected array, received object'
    }
  ],
  addIssue: [Function (anonymous)],
  addIssues: [Function (anonymous)],
  errors: [
    {
      code: 'invalid_type',
      expected: 'array',
      received: 'object',
      path: [ 'andSomethingLikeThat', 'example2Categories', 0 ],
      message: 'Expected array, received object'
    },
    {
      code: 'invalid_type',
      expected: 'array',
      received: 'object',
      path: [ 'andSomethingLikeThat', 'example2Categories', 1 ],
      message: 'Expected array, received object'
    },
    {
      code: 'invalid_type',
      expected: 'array',
      received: 'object',
      path: [ 'andSomethingLikeThat', 'example2Categories', 2 ],
      message: 'Expected array, received object'
    }
  ]
}

Node.js v20.12.0
 ELIFECYCLE  Command failed with exit code 1.

```

Finally, note that I got the exact same result by trying:
* `z.array(z.string()).array().optional()` instead of `z.array(z.array(z.string())).optional()`
* `z.array(z.string()).array()` instead of `z.array(z.array(z.string())).optional()`

### Expected behavior

* If arrays of arrays must not supported by design, by zod-matter, then the error message should clearly state that: for the motment, `zod-matter` throws an error, stating that an array was expected, but an object was received. Which is not true, it is inded an array which was received, as expected
* If arrays of arrays must be supported by zod-matter, then we should successufully get the array of arrays extracted from frontmatter

### How often does this bug happen?

Every time

### System Info

- operating system: Windows 10 pro
- `NodeJS` version: `v20.12.0`

**Comment by Jean-Baptiste-Lasselle** [comment]
Moreover, @HiDeoo I have tested parsing the same markdown with `gray-matter`, and I do not get any error, plus graymatter does recognize the `example2Categories` property as an array:


```TypeScript

import * as grayMatter from 'gray-matter'; // pnpm add --save gray-matter

const someMarkdown2 = `---\n
author: HiDeoo\n
andSomethingLikeThat:\n
  firstname: Jean-Baptiste\n
  lastname: Lasselle\n
  one: true\n
  two: 12\n
  three: false\n
  example1Categories: \n
    - design\n
    - terraform\n
    - plugin\n
  example2Categories: \n
    - first:\n
        - joe\n
        - alfred\n
        - alvin\n
    - second:\n
        - thirteen\n
        - hundred\n
        - books\n
    - third:\n
        - going\n
        - overseas\n
        - together\n
---\n
# Hello HiDeeo!
`

console.log(` Final result parsing someMarkdown using gray-matter gives:`)

console.log(grayMatter.test(someMarkdown));
console.log(grayMatter.language(someMarkdown));
console.log(grayMatter.default(someMarkdown));
```

Result Output:

```bash

 Final result parsing someMarkdown2 using gray-matter gives:
true
{ raw: '', name: '' }
{
  content: '\n# Hello HiDeeo!\n',
  data: {
    author: 'HiDeoo',
    andSomethingLikeThat: {
      firstname: 'Jean-Baptiste',
      lastname: 'Lasselle',
      one: true,
      two: 12,
      three: false,
      example1Categories: [Array],
      example2Categories: [Array]
    }
  },
  isEmpty: false,
  excerpt: '',
  orig: <Buffer 2d 2d 2d 0a 0a 61 75 74 68 6f 72 3a 20 48 69 44 65 6f 6f 0a 0a 61 6e 64 53 6f 6d 65 74 68 69 6e 67 4c 69 6b 65 54 68 61 74 3a 0a 0a 20 20 66 69 72 73 ... 419 more bytes>
}

```

**Comment by HiDeoo** [comment]
Thanks for the detailed feedback.

> Moreover, @HiDeoo I have tested parsing the same markdown with `gray-matter`, and I do not get any error, plus graymatter does recognize the `example2Categories` property as an array:

This is correct, altho I don't think the log in your example are enough to reliably say that `gray-matter` is working as you expect. Is it an array of strings as you expect or something else?

By running the exact same example as your last one but instead of logging `grayMatter.default(someMarkdown);`, let's log `grayMatter(someMarkdown).data`:

```
 Final result parsing someMarkdown using gray-matter gives:
true
{ raw: '', name: '' }
{
  author: 'HiDeoo',
  andSomethingLikeThat: {
    firstname: 'Jean-Baptiste',
    lastname: 'Lasselle',
    one: true,
    two: 12,
    three: false,
    example1Categories: [ 'design', 'terraform', 'plugin' ],
    example2Categories: [ [Object], [Object], [Object] ]
  }
}
```

This does not looks like an array of string arrays but more like an array of objects. This also seems to match the error returned by `zod-matter` ("Expected array, received object") but `zon-matter` is not involved in this last example.

If we log the content of the parsed `example2Categories` property, we can see a bit more clearly what is going on:

```
[
  { first: [ 'joe', 'alfred', 'alvin' ] },
  { second: [ 'thirteen', 'hundred', 'books' ] },
  { third: [ 'going', 'overseas', 'together' ] }
]
```

And this output is correct and matching your frontmatter so `zod-matter` is working as expected as it's not getting an array of string arrays and thus throwing an error.

Switching back to your first example, now the question would be, is the frontmatter wrong or is the schema wrong? If you really want to have an array of string arrays, the frontmatter should be updated to match that:

```js
const someMarkdown = `---\n
author: HiDeoo\n
andSomethingLikeThat:\n
  firstname: Jean-Baptiste\n
  lastname: Lasselle\n
  one: true\n
  two: 12\n
  three: false\n
  example1Categories: \n
    - design\n
    - terraform\n
    - plugin\n
  example2Categories: \n
    - - joe\n
      - alfred\n
      - alvin\n
    - - thirteen\n
      - hundred\n
      - books\n
    - - going\n
      - overseas\n
      - together\n
---\n
# Hello HiDeoo!
`;
```

Running this markdown with `zod-matter` and `example2Categories` expecting `z.array(z.array(z.string())).optional()` will work as expected:

```js
[
  [ 'joe', 'alfred', 'alvin' ],
  [ 'thirteen', 'hundred', 'books' ],
  [ 'going', 'overseas', 'together' ]
]
```

If on the contrary, the frontmatter is correct, you would need to update the schema of `example2Categories` to something like `z.array(z.record(z.string().array())).optional()`:

```js
[
  { first: [ 'joe', 'alfred', 'alvin' ] },
  { second: [ 'thirteen', 'hundred', 'books' ] },
  { third: [ 'going', 'overseas', 'together' ] }
]
```

**Comment by Jean-Baptiste-Lasselle** [comment]
> Thanks for the detailed feedback.
> 
> > Moreover, @HiDeoo I have tested parsing the same markdown with `gray-matter`, and I do not get any error, plus graymatter does recognize the `example2Categories` property as an array:
> 
> This is correct, altho I don't think the log in your example are enough to reliably say that `gray-matter` is working as you expect. Is it an array of strings as you expect or something else?
> 
> By running the exact same example as your last one but instead of logging `grayMatter.default(someMarkdown);`, let's log `grayMatter(someMarkdown).data`:
> 
> ```
>  Final result parsing someMarkdown using gray-matter gives:
> true
> { raw: '', name: '' }
> {
>   author: 'HiDeoo',
>   andSomethingLikeThat: {
>     firstname: 'Jean-Baptiste',
>     lastname: 'Lasselle',
>     one: true,
>     two: 12,
>     three: false,
>     example1Categories: [ 'design', 'terraform', 'plugin' ],
>     example2Categories: [ [Object], [Object], [Object] ]
>   }
> }
> ```
> 
> This does not looks like an array of string arrays but more like an array of objects. This also seems to match the error returned by `zod-matter` ("Expected array, received object") but `zon-matter` is not involved in this last example.
> 
> If we log the content of the parsed `example2Categories` property, we can see a bit more clearly what is going on:
> 
> ```
> [
>   { first: [ 'joe', 'alfred', 'alvin' ] },
>   { second: [ 'thirteen', 'hundred', 'books' ] },
>   { third: [ 'going', 'overseas', 'together' ] }
> ]
> ```
> 
> And this output is correct and matching your frontmatter so `zod-matter` is working as expected as it's not getting an array of string arrays and thus throwing an error.
> 
> Switching back to your first example, now the question would be, is the frontmatter wrong or is the schema wrong? If you really want to have an array of string arrays, the frontmatter should be updated to match that:
> 
> ```js
> const someMarkdown = `---\n
> author: HiDeoo\n
> andSomethingLikeThat:\n
>   firstname: Jean-Baptiste\n
>   lastname: Lasselle\n
>   one: true\n
>   two: 12\n
>   three: false\n
>   example1Categories: \n
>     - design\n
>     - terraform\n
>     - plugin\n
>   example2Categories: \n
>     - - joe\n
>       - alfred\n
>       - alvin\n
>     - - thirteen\n
>       - hundred\n
>       - books\n
>     - - going\n
>       - overseas\n
>       - together\n
> ---\n
> # Hello HiDeoo!
> `;
> ```
> 
> Running this markdown with `zod-matter` and `example2Categories` expecting `z.array(z.array(z.string())).optional()` will work as expected:
> 
> ```js
> [
>   [ 'joe', 'alfred', 'alvin' ],
>   [ 'thirteen', 'hundred', 'books' ],
>   [ 'going', 'overseas', 'together' ]
> ]
> ```
> 
> If on the contrary, the frontmatter is correct, you would need to update the schema of `example2Categories` to something like `z.array(z.record(z.string().array())).optional()`:
> 
> ```js
> [
>   { first: [ 'joe', 'alfred', 'alvin' ] },
>   { second: [ 'thirteen', 'hundred', 'books' ] },
>   { third: [ 'going', 'overseas', 'together' ] }
> ]
> ```

That is true! Thank you very much for that quick feedback! 

* As a thank you, I today commit to explain why I was testing this slightly extremist array of arrays in a frontmatter, in the next months, I keep that secret until I release something which will give you the base of my explanation
* In less than 6 months, I will be able to give a full exaplanation: thank you very much for your work, `zod-matter` helped me running some tests on my current work.

**Comment by Jean-Baptiste-Lasselle** [comment]
I worked a bit more, and also found, and wanted to give you, the zod schema validating the pathologic frontmatter i gave first:

```TypeScript
const someMarkdown3 = `---\n
author: HiDeoo\n
andSomethingLikeThat:\n
  firstname: Jean-Baptiste\n
  lastname: Lasselle\n
  one: true\n
  two: 12\n
  three: false\n
  example1Categories: \n
    - design\n
    - terraform\n
    - plugin\n
  example2Categories: \n
    - first:\n
        - joe\n
        - alfred\n
        - alvin\n
    - second:\n
        - thirteen\n
        - hundred\n
        - books\n
    - third:\n
        - going\n
        - overseas\n
        - together\n
---\n
# Hello Zod Tuples!
`

const schemaForMarkdown3 = z.object({
  author: z.string(),
  andSomethingLikeThat: z.object({
    firstname: z.string(),
    lastname: z.string(),
    one: z.boolean(),//true
    two: z.number(),//12
    three: z.boolean(),//false
    example1Categories: z.array(z.string()),//
    example2Categories: z.tuple([
      z.object({first: z.array(z.string())}),
      z.object({second: z.array(z.string())}),
      z.object({third: z.array(z.string())}),
    ])
  })
})
```
